### PR TITLE
Initial implementation of pure-go commP calculator

### PR DESCRIPTION
**Pull request by ribasushi**
This is a pure-go ( no need to muck with ffi ) simplified version of a commP calculator. Mainly requested by @jsign, who as payment in return will add tests to this repo ( the code is feature complete, but no time-budget for tests at present ).

Includes a simple program to demonstrate how things work. See demo below of zero-effort pad-in-flight, of interest to @whyrusleeping.

/cc @rvagg @vmx for cursory review  ( I know both of you worked on similar code before )


```
~$ dd if=/dev/urandom bs=23172313 count=1 of=random.file                                                                                                                                                                                                          
23172313 bytes (23 MB, 22 MiB) copied, 0.0885575 s, 262 MB/s

~$ lotus client generate-car random.file random.car                                                                   
~$ lotus client commP random.car                                                                                      
CID:  baga6ea4seaqj4qipweaxhrpcvstzbrnuzojazrdyfyuxzzdyjcm62m5lbq3jkhi 
Piece size:  31.75 MiB

~$ ls -l random.car 
-rw-rw-r-- 1 ubuntu ubuntu 23174562 Mar 22 19:39 random.car

~$ ipfs add --pin=false --cid-version 1 --chunker size-$(( 1024*1024 )) --hash blake2b-256 ~/random.file | grep -oE 'bafy\S*' | xargs ipfs dag export | go run ./
2021/03/22 19:39:55 Reading from STDIN...
2021/03/22 19:39:55 Finished:
CommP:    9e410fb10173c5e2aca790c5b4cb920cc4782e297ce4784899ed33ab0c36951d
CommPCid: baga6ea4seaqj4qipweaxhrpcvstzbrnuzojazrdyfyuxzzdyjcm62m5lbq3jkhi
Raw bytes:          23174562 bytes
Unpadded piece:     33292288 bytes
Padded piece:       33554432 bytes
```

And now the same with padding...
```
~$ ipfs add --pin=false --cid-version 1 --chunker size-$(( 1024*1024 )) --hash blake2b-256 ~/random.file | grep -oE 'bafy\S*' | xargs ipfs dag export | go run ./ -t 8589934592
2021/03/22 19:40:11 Reading from STDIN...
2021/03/22 19:40:11 Finished:
CommP:    0f9dbe3ca4ebdabc9ea2f1e0eb8ec04403dc5f62c2db83fd53ec41f8304ee639
CommPCid: baga6ea4seaqa7hn6hssoxwv4t2rpdyhlr3aeia64l5rmfw4d7vj6yqpygbhomoi
Raw bytes:          23174562 bytes
Unpadded piece:   8522825728 bytes
Padded piece:     8589934592 bytes


~$ fallocate -l 8522825728 random.car 

~$ ls -l random.car                                                                                                   
-rw-rw-r-- 1 ubuntu ubuntu 8522825728 Mar 22 19:40 random.car

~$ lotus client commP random.car
CID:  baga6ea4seaqa7hn6hssoxwv4t2rpdyhlr3aeia64l5rmfw4d7vj6yqpygbhomoi
Piece size:  7.938 GiB

```

### CODE REVIEW

**Comment by rvagg** [comment]
:shrug: if you're getting the same results then that's a good sign. I'm not seeing the fr32 padding of the input data as an obvious part of this process here, the extra 2 zero-bits per every 254 bits. I see something about 127 bytes, adding additional bytes, and I'm not sure what that's about. But if the commp is the same then I guess it's coming together.

**Comment by rvagg** [comment]
probably not helpful, but my JS impl worked and has a more explicit fr32 pad process https://github.com/rvagg/js-fil-utils

**Comment by ribasushi** [comment]
> probably not helpful, but my JS impl 

it was very helpful actually way way back when I was researching how to write this efficiently last summer, there was just never an impetus to package this until now.

> the extra 2 zero-bits per every 254 bits

It's right here: https://github.com/filecoin-project/go-fil-commp-hashhash/blob/feat/init/commp.go#L209-L264, except that instead of working through larger chunks like you did, I work over the shortest-period range of 127 bytes, which produces 128 bytes after the padding shifts, and then at byte 129 you start again from scratch. Since the tree builder consumes pieces in 32 byte increments it works out all the same.

**Comment by ribasushi** [comment]
@rvagg I was too asleep when I wrote:
> I work over the shortest-period range of 127 bytes, which produces 128 bytes after the padding shifts

To clarify: the fr32 expansion works over 254 bits of payload. The first integer amount of bytes that is divisible by 254 bits is lcm(254,8) == 1016 == 127 bytes. Since the padding with zeroes can happen both during tree construction and during fr32 without affecting the result, I elect to always process the incoming stream in 127byte chunks, applying the fr32 transform on that entire 127-member array in a single pass, and ending up with 4 commp DAG leaves in the process.

**Comment by rvagg** [comment]
> https://github.com/filecoin-project/go-fil-commp-hashhash/blob/feat/init/commp.go#L209-L264

yeah, ok, you're making me feel like an absolute brainlet but whatever

I also see `stackedNulPadding[i][31] &= 0x3F` to make `sha2-256-trunc254-padded` so that's the other ✅ 

all good then if it's getting consistently same results

**Comment by ribasushi** [comment]
@jsign just flagging that I am effectively done with this library. Please let me know whether you need anything extra aside from what's available and whether you will have some tests to contribute. Otherwise I will merge this as-is around March 31st.

Thanks!

**Comment by jsign** [comment]
> @jsign just flagging that I am effectively done with this library. Please let me know whether you need anything extra aside from what's available and whether you will have some tests to contribute. Otherwise I will merge this as-is around March 31st.
> 
> Thanks!

I think it's great as it is! 
I'll be proposing some PR this/next week as to add some tests.

**Pull request merged**
